### ISSUE TITLE
git clone: error setting certificate verify locations

### ISSUE THREAD

**Issue by lookfwd** [scalingexcellence/scrapybook#36]
Getting this error while cloning the book:

```
C:\Users\me> git clone https://github.com/scalingexcellence/scrapybook.git
Cloning into 'scrapybook'...
fatal: unable to access 'https://github.com/scalingexcellence/scrapybook.git/':
error setting certificate verify locations:
  CAfile: C:\Program Files\Git\mingw64/bin/curl-ca-bundle.crt
  CApath: none
```

**Comment by lookfwd** [comment]
A temporary fix is to use `GIT_SSL_NO_VERIFY` to disable ssl checking.

```
set GIT_SSL_NO_VERIFY=true 
git clone...
```

**Comment by vetom** [comment]
Installing Git again will fix this error.

**Comment by JayaniSumudini** [comment]
`git config --global http.sslverify "false"`
This command resolve my problem

**Comment by KA24956T** [comment]
still i am getting same error

**Comment by yellu123** [comment]
> `git config --global http.sslverify "false"`
> This command resolve my problem

why it came what was the problem

**Comment by yellu123** [comment]
why i need to use this command

**Comment by guimmp92** [comment]
> why i need to use this command

It disables verification for all certificates.

**Comment by kokhapp** [comment]
@lookfwd Thank you very much

**Comment by bouksy** [comment]
Got the same issue, used SSH public key...more convenient for lazy dudes like me :)

**Comment by NoBrainer** [comment]
It's a better solution to get the `ca-bundle.crt` file and update the git config to use it with:
```bash
git config http.sslCAinfo "/path/to/ca-bundle.crt"
```

**Comment by Utkarsh-Gangal** [comment]
Awesome, this works

**Comment by boiindo** [comment]
@NoBrainer hey , I tried doing it . but it is not working . can you please help. still shows   
CAfile: C:\Program Files\Git\mingw64/bin/curl-ca-bundle.crt
it is a mac OS.

**Comment by NoBrainer** [comment]
@boiindo, it looks like you're mixing Windows and UNIX-based path syntax. You probably want something more like:
`git config http.sslCAinfo "/c/Program Files/Git/mingw64/bin/curl-ca-bundle.crt"`

(Make sure you verify that the path is correct by doing something like: `cd /c/Program Files/Git/mingw64/bin`.)

**Comment by boiindo** [comment]
@NoBrainer thanx for replying. I did notice the mixing of 2 syntax. Donot understand how a windows path is present in macos. tried searching for curl-ca-bundle, couldn't find it. tried exporting certificates into a .pem file , fatal not in git directory ( should i add the file in the bin) . when working with git config , it says no access. 

Kindly help. Can I download certificates from somewhere (don't know authentic places) and place it in the git directory ?

**Comment by NoBrainer** [comment]
You'll need to check inside of the directory where git is installed. From there, it should be something like this: `mingw64/ssl/certs/ca-bundle.crt`. (If you do not find this, you probably have an outdated version of git, so you should reinstall it first.)

**Comment by ahamaz** [comment]
Hi @boiindo, I have windows 10 and cert is at same location as you mentioned [Git/mingw64/ssl/certs/ca-bundle.crt]. and i am having this error and jenkins is unable to proceed further.

fatal: unable to access 'https://github.com/redis.git/': error setting certificate verify locations:
CAfile: C:Usersrichardahasan.manzoor.alieclipse
CApath: none

while when i am running this command on cmd: git config --list

diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Users/ahasan.manzoor.ali/AppData/Local/Programs/Git/usr/bin/curl-ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager
user.name=ahamaz
user.email=ahasanfsm@hotmail.com
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
filter.lfs.clean=git-lfs clean -- %f
http.sslcainfo=C:Usersahasan.manzoor.alieclipse
http.sslcainfo=C:Usersahasan.manzoor.alieclipse
http.schannelcheckrevoke=false

Actually I am running multi branch. i used the above suggestions to disable verification but that is working in cmd, while build from jenkins is still there.
Please advise how this issue could be resolved.

**Comment by ahamaz** [comment]
when I am running this command,
$ git config http.sslCAinfo "C:\Users\ahasan.manzoor.ali\AppData\Local\Programs\Git\mingw64\ssl\certs\ca-bundle.crt"
fatal: not in a git directory

**Comment by Erasmus24** [comment]
Thanks guys, the following has helped me to fix the issue:

git config --global http.sslverify "false"

**Comment by pranavdj9** [comment]
> `git config --global http.sslverify "false"`
> This command resolve my problem

Thank you soo sooo much
I got frustrated because it wasn't working , thank you!!!!!

**Comment by NoBrainer** [comment]
@Erasmus24 & @pranavdj9, by turning off `http.sslverify`, you are treating the symptom instead of solving the problem. You should fix the certificate issue instead of downgrading your security. This is only acceptable when debugging or working with a prototype.

**Comment by pranavdj9** [comment]
Well... I really don’t know  how to fix that, I tried searching the internet... but didn’t find anything relatable. If you know how to do it, then pls tell me

**Comment by NoBrainer** [comment]
@pranavdj9, you need to find where `ca-bundle.crt` is located within the Git installation. If you can't find it, you probably have to update/reinstall Git. Once you find the file, you can run: `git config http.sslCAinfo "/path/to/ca-bundle.crt"`

**Comment by pranavdj9** [comment]
Thanks so much
I will definitely try it

**Comment by pranavdj9** [comment]
When I ran the code I got this fatal error :
fatal: not in a git directory
BTW the ca-bundle.crt was in the git installation files

**Comment by nu8** [comment]
I had this problem as well. My issue was this file:

~~~
/usr/ssl/certs/ca-bundle.crt
~~~

if by default just an empty file. So even if it exists, youll still get the
error as it doesnt contain any certificates. You can generate them like this:

~~~
p11-kit extract --overwrite --format pem-bundle /usr/ssl/certs/ca-bundle.crt
~~~

**Comment by vershiy** [comment]
Thanks Steve I really appreciate

**Comment by BevilaquaBruno** [comment]
I was getting the same error, and i resolved it with this steps:
   1. Unnistall Git from your PC, and remove the folder remained(Git/etc).
   2. Access your path variables and remove the git from all the users and the general path.
   3. Install git again running as admin.

**Comment by RachaelMuthoni** [comment]
While installing git I enabled the git credential manager. Weeell, I clicked next next next finish 
without customizing anything. But when am pushing my code to my github account and am about to complete authentication by authorizing the git credential manager, am unable to because where am supposed to click has been disabled.
![image](https://user-images.githubusercontent.com/75661500/103879811-2bc6ed00-508d-11eb-9f95-49e11272af05.png)

**Comment by RachaelMuthoni** [comment]
Helloooo, I got a solution to my problem an am happy. I was using Microsoft edge a my default browser and it had no certificates for verification. That is why the button "authorize git credential manager" was disabled. Thanks to me😊

**Comment by SereneFeng** [comment]
One possible reason you're getting that error is because this path C:\Program Files\Git\mingw64/bin/curl-ca-bundle.crt (which is the CA file path shown in the error message) is NOT where your curl-ca-bundle.crt is located. 
I went into program files (file explorer) and found that my CA file was located at D:\ProgramFiles(D)\Git\mingw64\ssl\certs\ca-bundle.crt. I had installed Git on a different location than they expected.

To tell Git to run on the correct path, run: `git config --system http.sslcainfo "YOUR PATH"`

example:
`git config --system http.sslcainfo "D:\ProgramFiles(D)\Git\mingw64\ssl\certs\ca-bundle.crt"`

After that, go ahead and run the git clone / git push / ect. stuff! Looks like the post author's next step is running `git clone https://github.com/scalingexcellence/scrapybook.git`

**Comment by samgreguc** [comment]
> @pranavdj9, you need to find where `ca-bundle.crt` is located within the Git installation. If you can't find it, you probably have to update/reinstall Git. Once you find the file, you can run: `git config http.sslCAinfo "/path/to/ca-bundle.crt"`

i know this reply is late but i am having same issue on my windows laptop. can you please guide me through?

**Comment by samgreguc** [comment]
@pranavdj9 here is the reply when I tried the git clone 

PS C:\Users\Samuel Greg> git clone https://github.com/flutter/flutter.git -b stable
>>
Cloning into 'flutter'...
fatal: unable to access 'https://github.com/flutter/flutter.git/': error setting certificate verify locations:  CAfile: C:/Path/To/CertBundle/ca-bundle.crt CApath: none
PS C:\Users\Samuel Greg>

**Comment by maxmonzon** [comment]
> It's a better solution to get the `ca-bundle.crt` file and update the git config to use it with:
> 
> ```shell
> git config http.sslCAinfo "/path/to/ca-bundle.crt"
> ```

This is by far the best answer. You should find the path of your git installation. Directory on windows should be something like this git config --global http.sslCAinfo "C:/<your path>/mingw64/ssl/certs/ca-bundle.crt"

Pay attention to set as a global configuration

**Comment by alejandro0619** [comment]
> git config --global http.sslverify "false"

This solved my error, thanks so much

**Comment by irenelopezruiz** [comment]
> Thanks guys, the following has helped me to fix the issue:
> 
> git config --global http.sslverify "false"

When I use this, it says: error: could not lock config file C:/Users/Irene/.gitconfig: Permission denied
 what can i solve it?

**Comment by Wakogemeda** [comment]
git config --global http.sslverify "false"
This command solve problem

**Comment by alejandro0619** [comment]
> > Thanks guys, the following has helped me to fix the issue:
> > git config --global http.sslverify "false"
> 
> When I use this, it says: error: could not lock config file C:/Users/Irene/.gitconfig: Permission denied what can i solve it?

Did you solved it?
You can run it using administrator privileges and see if it works. By the way, this stackoverflow threat have many fixes: https://stackoverflow.com/questions/55327408/how-to-fix-git-for-windows-error-could-not-lock-config-file-c-file-path-to-g

**Comment by amjadjamali06** [comment]
`git config --global http.sslverify "false"`

My Problem is solved using this command.

Thanks  [JayaniSumudini](https://github.com/JayaniSumudini)  👍🏻

**Comment by amjadjamali06** [comment]
> `git config --global http.sslverify "false"` This command resolve my problem

My Problem is solved using this command.

Thanks [JayaniSumudini](https://github.com/JayaniSumudini) 👍🏻

**Comment by Philippe-OPC** [comment]
> It's a better solution to get the `ca-bundle.crt` file and update the git config to use it with:
> 
> ```shell
> git config http.sslCAinfo "/path/to/ca-bundle.crt"
> ```

This is the line we all need, it works like a charm for me, but be sure to have only that line and not `http.sslCApath` and use `--system` to apply system-wide
Here is my command :
`sudo git config --system http.sslCAinfo /usr/local/share/ca-certificates/zscaler.crt`

Here is my file :                                         
```
[http]
        sslCAinfo = /usr/local/share/ca-certificates/zscaler.crt
```

Disabling ssl was not an option for me

**Comment by Remigiusz-Gabryel** [comment]
Like other suggested.  `git config --system http.sslCAinfo "C:\Program Files\Git\mingw64\ssl\certs\ca-bundle.crt"` - worked, just remember to run this command in Terminal opened with administrator privilege... I didn't, I suffered for 20 minutes.

**Comment by Coeliman** [comment]
Is there any difference when you are using the portable version of git to fix this?

Using the `git config --system http.sslCAinfo "C:\Users\usr\Downloads\PortableGit\mingw64\ssl\certs/ca-bundle.crt"` works, but I still get the same error when attempting to pull code.

**Comment by Coeliman** [comment]
Did the command that supposedly fixes it, went through successfully. Yet I am still getting the same error, I am using portablegit and do not have administrative permissions on this PC. Any ideas?

**Comment by sethWines** [comment]
I had this issue as well. Hopefully I'm not repeating an answer but I figured I'd document a cause. I had renamed the "User" folder where git was installed. I had already updated my $PATH variables but I didn't update any git configs. 

Old Directory   T:\**oldname**\Git\mingw64\ssl\certs\ca-bundle.crt
New Directory  T:\**newname**\Git\mingw64\ssl\certs\ca-bundle.crt

So I just used this like many others posted above:
`git config --global http.sslCAInfo T:\newname\Git\mingw64\ssl\certs\ca-bundle.crt`

**Comment by Coeliman** [comment]
For me it was another issue. Had a friend much more experienced with git then me help fix it.
They fixed it by running `git config --global http.sslbackend schannel`

They found it off of here: https://github.com/microsoft/Git-Credential-Manager-for-Windows/issues/646

**Comment by Commod0re** [comment]
in my case this was caused by my `ca-bundle.crt` was owned by the wrong user and not readable by others, `chmod a+r ca-bundle.crt` fixed it

**Comment by marwanm-dev** [comment]
> For me it was another issue. Had a friend much more experienced with git then me help fix it. They fixed it by running `git config --global http.sslbackend schannel`
> 
> They found it off of here: [microsoft/Git-Credential-Manager-for-Windows#646](https://github.com/microsoft/Git-Credential-Manager-for-Windows/issues/646)

Solved it for me

**Comment by dennisokafor** [comment]
This worked for me, Thanks !

**Comment by dennisokafor** [comment]
> > For me it was another issue. Had a friend much more experienced with git then me help fix it. They fixed it by running `git config --global http.sslbackend schannel`
> > They found it off of here: [microsoft/Git-Credential-Manager-for-Windows#646](https://github.com/microsoft/Git-Credential-Manager-for-Windows/issues/646)
> 
> Solved it for me



> > For me it was another issue. Had a friend much more experienced with git then me help fix it. They fixed it by running `git config --global http.sslbackend schannel`
> > They found it off of here: [microsoft/Git-Credential-Manager-for-Windows#646](https://github.com/microsoft/Git-Credential-Manager-for-Windows/issues/646)
> 
> Solved it for me

This worked for me

**Comment by sajid365-sr** [comment]
> `git config --global http.sslverify "false"` This command resolve my problem

Thanks...It works for me

**Comment by mrkhadus** [comment]
It just happens if we are using the old version of the git, 
updating the git should solve this issue. 
cmd: "git update-git-for-windows"

**Comment by ALNAshef** [comment]
I got the same problem, I re-installed git and it works.

**Comment by umeshbedi** [comment]
> ca-bundle.crt

best method

**Comment by NoCode4real** [comment]
> `git config --global http.sslverify "false"` This command resolve my problem

Thank you so much solved the problem 👍

**Comment by smtmRadu** [comment]
> git config --global http.sslverify "false"

worked for me

**Comment by motazreda** [comment]
guys the path just changed `git config --global http.sslcainfo "C:\Program Files\Git\mingw64\etc\ssl\certs\ca-bundle.crt"`

ssl folder is now inside etc folder.

**Comment by SanicBTW** [comment]
> For me it was another issue. Had a friend much more experienced with git then me help fix it. They fixed it by running `git config --global http.sslbackend schannel`
> 
> They found it off of here: [microsoft/Git-Credential-Manager-for-Windows#646](https://github.com/microsoft/Git-Credential-Manager-for-Windows/issues/646)

Worked for me!

**Comment by nIsratJahan20002** [comment]
> > `git config --global http.sslverify "false"`
> > This command resolve my problem
> 
> why it came what was the problem

yeah this command really working .

**Comment by Santosh-2605** [comment]
git config --global http.sslverify "false"

This command is working indeed. Thank you all
